[test]
preload = ["./test/setup.ts"]
coverageReporter = ["text", "lcov"]
coverageThreshold = { lines = 0.99, functions = 1.0, statements = 0.99 }
coveragePathIgnorePatterns = [
  "src/hub.entry.ts",
  "src/games/crown.ts",
  "src/games/flux.ts",
  "src/games/lex.ts",
]
