import type {
  BlockFactory,
  BlockHandle,
  BlockKind,
  BlockOutcome,
} from "../engine/block";
import { BASE } from "../shared/base";
import { BRAIN_PATHS, iconSvg, mountQuitButton } from "../shared/icons";
import {
  getDailyHistory,
  recordDaily,
  recordSessionScore,
  todayString,
} from "../shared/progress";
import { resetRng, seededRng, setRng } from "../shared/rng";
import * as sound from "../shared/sounds";
import { recordResult } from "../shared/stages";
import { initTheme, wireToggle } from "../shared/theme";
import { createCrownBlock } from "./crown-block";
import { createFluxBlock } from "./flux-block";
import { createLexBlock } from "./lex-block";

interface DailyStep {
  kind: BlockKind;
  label: string;
  accent: string;
  factory: BlockFactory;
  maxTrials: number;
}

const TRANSITION_MS = 800;
const HISTORY_DAYS = 7;

/**
 * Same block-sequence design as Cycle, but every trial is generated by a
 * date-seeded PRNG so a given date produces the same trials for every
 * replay — self-vs-self leaderboard, no luck-of-the-draw across attempts.
 *
 * Engine RNG is swapped in setRng/resetRng around the whole run; quit
 * paths restore the default Math.random so other surfaces (e.g. nav-back
 * to hub) are not left with a seeded global.
 */
const STEPS: readonly DailyStep[] = [
  {
    kind: "lex",
    label: "Lex",
    accent: "var(--ctp-blue)",
    factory: createLexBlock,
    maxTrials: 8,
  },
  {
    kind: "crown",
    label: "Crown",
    accent: "var(--ctp-green)",
    factory: createCrownBlock,
    maxTrials: 8,
  },
  {
    kind: "flux",
    label: "Flux",
    accent: "var(--ctp-red)",
    factory: createFluxBlock,
    maxTrials: 15,
  },
] as const;

function getEl(id: string): HTMLElement {
  const el = document.getElementById(id);
  if (el === null) {
    throw new Error(`Missing #${id} element`);
  }
  return el;
}
const game = getEl("game");

let stepIdx = 0;
let outcomes: BlockOutcome[] = [];
let activeHandle: BlockHandle | null = null;
let dailyAborted = false;
let transitionTimeout: ReturnType<typeof setTimeout> | null = null;
const today = todayString();

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderShell(): void {
  const stepperHtml = STEPS.map((step, i) => {
    const state =
      i < stepIdx ? "is-done" : i === stepIdx ? "is-active" : "is-pending";
    return `<div class="cycle-step ${state}" style="--step-accent:${step.accent}">
      <span class="cycle-step-dot"></span>
      <span class="cycle-step-name">${escapeHtml(step.label)}</span>
    </div>`;
  }).join("");
  game.innerHTML = `
    <div class="daily-tagline">Daily Challenge · ${escapeHtml(today)}</div>
    <div class="cycle-stepper" role="progressbar"
         aria-label="Daily progress"
         aria-valuemin="0" aria-valuemax="${String(STEPS.length)}" aria-valuenow="${String(stepIdx)}">${stepperHtml}</div>
    <div class="cycle-slot" id="cycle-slot"></div>
  `;
}

function slot(): HTMLElement {
  return getEl("cycle-slot");
}

function setAccent(accent: string): void {
  document.documentElement.style.setProperty("--game-accent", accent);
}

function renderTransition(nextStep: DailyStep): void {
  const s = slot();
  s.innerHTML = `
    <div class="cycle-transition" style="--step-accent:${nextStep.accent}">
      <div class="cycle-transition-label">Next block</div>
      <div class="cycle-transition-name">${escapeHtml(nextStep.label)}</div>
    </div>
  `;
}

function clearTransition(): void {
  if (transitionTimeout !== null) {
    clearTimeout(transitionTimeout);
    transitionTimeout = null;
  }
}

function startStep(): void {
  if (dailyAborted) {
    showSummary();
    return;
  }
  const step = STEPS[stepIdx];
  if (!step) {
    showSummary();
    return;
  }
  setAccent(step.accent);
  renderShell();
  activeHandle = step.factory({
    container: slot(),
    maxTrials: step.maxTrials,
    onComplete: (outcome) => {
      activeHandle = null;
      outcomes.push(outcome);
      recordSessionScore(step.kind, outcome.points);
      recordResult(step.kind, outcome.accuracy);
      stepIdx++;
      if (dailyAborted || stepIdx >= STEPS.length) {
        showSummary();
        return;
      }
      const next = STEPS[stepIdx];
      if (!next) {
        showSummary();
        return;
      }
      renderShell();
      renderTransition(next);
      transitionTimeout = setTimeout(() => {
        transitionTimeout = null;
        startStep();
      }, TRANSITION_MS);
    },
  });
}

function renderHistory(totalPoints: number): string {
  // Persist before we render so today's row reflects the just-finished score.
  if (!dailyAborted) {
    recordDaily(today, totalPoints);
  }
  const rows = getDailyHistory(today, HISTORY_DAYS);
  const cells = rows
    .slice()
    .reverse()
    .map((row) => {
      const isToday = row.date === today;
      const empty = row.score === null;
      const cls = [
        "daily-history-cell",
        isToday ? "is-today" : "",
        empty ? "is-empty" : "",
      ]
        .filter(Boolean)
        .join(" ");
      const day = new Date(`${row.date}T00:00:00`)
        .toLocaleDateString("en-US", { weekday: "short" })
        .slice(0, 2);
      const scoreHtml = empty
        ? `<span class="daily-history-empty">—</span>`
        : `<span class="daily-history-score">${String(row.score)}</span>`;
      return `<div class="${cls}" title="${escapeHtml(row.date)}">
        <span class="daily-history-day">${escapeHtml(day)}</span>
        ${scoreHtml}
      </div>`;
    })
    .join("");
  return `<div class="daily-history">${cells}</div>`;
}

function showSummary(): void {
  clearTransition();
  resetRng();
  const totalPoints = outcomes.reduce((acc, o) => acc + o.points, 0);
  const tiles = STEPS.map((step, i) => {
    const out = outcomes[i];
    const points = out?.points ?? 0;
    const accuracy = out ? Math.round(out.accuracy * 100) : 0;
    const trials = out?.trials ?? 0;
    const metaLine = out
      ? `${String(accuracy)}% · ${String(trials)} trial${trials === 1 ? "" : "s"}`
      : "skipped";
    return `<div class="cycle-block-tile" style="--tile-accent:${step.accent}">
      <div class="cycle-block-tile-name">${escapeHtml(step.label)}</div>
      <div class="cycle-block-tile-points">${String(points)}</div>
      <div class="cycle-block-tile-meta">${escapeHtml(metaLine)}</div>
    </div>`;
  }).join("");

  game.innerHTML = `
    <div class="result cycle-summary">
      <div class="cycle-summary-totals">
        <div class="cycle-summary-points">${String(totalPoints)}</div>
        <div class="cycle-summary-points-label">total points</div>
      </div>
      <div class="cycle-block-grid">${tiles}</div>
      ${renderHistory(totalPoints)}
      <div class="cycle-summary-actions">
        <button id="again-btn">Play Again</button>
        <button id="back-btn" class="secondary">Back to Hub</button>
      </div>
    </div>
  `;
  sound.playVictory();
}

function startDaily(): void {
  dailyAborted = false;
  stepIdx = 0;
  outcomes = [];
  setRng(seededRng(`daily-${today}`));
  startStep();
}

game.addEventListener("click", (e) => {
  const target = (e.target as HTMLElement).closest<HTMLElement>("button");
  if (!target) return;
  if (target.id === "again-btn") {
    startDaily();
  } else if (target.id === "back-btn") {
    window.location.href = `${BASE}?completed=daily`;
  }
});

mountQuitButton(() => {
  dailyAborted = true;
  clearTransition();
  if (activeHandle !== null) {
    activeHandle.abort();
  } else {
    showSummary();
  }
});

startDaily();

initTheme();
wireToggle();

const titleSlot = document.querySelector(".app-title");
if (titleSlot) {
  titleSlot.insertAdjacentHTML(
    "afterbegin",
    iconSvg(BRAIN_PATHS, { size: 20, stroke: "var(--ctp-yellow)" }),
  );
}
